language: java
os: windows
notifications:
  email:
    recipients:
      - praveenkumaryalamaddi@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
  irc:
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"

jdk:
  - oraclejdk8
